### PR TITLE
Pre-generate `src/tables.rs`: Rm all build-deps & `build.rs`

### LINKED ISSUE #7: Pre-generate `tables.rs` instead of doing it in `build.rs`?
Generating `tables.rs` requires `unicode-linebreak` to pull in `regex` and `hashbrown` as build-dependencies, plus running the generation at compile-time, which makes compilation a lot slower.

Since `LineBreak.txt` doesn't change that often, generating it manually won't make it much harder to maintain,

I can submit a PR to convert the `build.rs` to a separate crate that is never published and can be run locally to consume the `LineBreak.txt` and generate `src/tables.rs`, does it sound good to you?

If you insist on keeping the `build.rs`, it might be a good idea to switch to regex-lite https://github.com/rust-lang/regex/issues/961

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #7 

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by NobodyXu** [comment]
@axelf4 I've verified that adding `src/tables.rs` to `Cargo.toml:include` does work but requires you to use `--allow-dirty` when `cargo-publish`.

I've verified that `cargo publish --allow-dirty` does include `src/tables.rs` and generates a crate tarball that pass all tests.

I've also included a `CONTRIBUTING.md` on how to build and publish this crate.

**Comment by NobodyXu** [comment]
I also added caching for generated `src/tables.rs` so that the ci runs under 1m.

**Comment by NobodyXu** [comment]
@axelf4 Hello, can you review this please?
Thank you!

**Comment by NobodyXu** [comment]
@axelf4 Pinging since this issue has been stale for one month

**Comment by axelf4** [comment]
Sorry, I have been too busy with my thesis to give this the attention it deserves. I promise to get to this within a week.

**Comment by NobodyXu** [comment]
@axelf4 Friendly ping as it has been stale for another 3 weeks

**Comment by axelf4** [comment]
Thanks and sorry for the delay! I made some stylistic changes and squashed the commits before merging.

**Comment by NobodyXu** [comment]
@axelf4 Thanks! Can we have a new release please?

**Comment by NobodyXu** [comment]
@axelf4 Thank you very much!

**Pull request merged**
